openapi: 3.0.0
info:
  title: Combined API Specification
  version: 1.0.0
paths:
  /auth/register:
    post:
      summary: Register a new user
      responses:
        '200':
          description: User registered successfully
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /auth/login:
    post:
      summary: Login user
      responses:
        '200':
          description: User logged in successfully
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /auth/refresh:
    post:
      summary: Refresh JWT token
      responses:
        '200':
          description: Token refreshed successfully
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /auth/logout:
    post:
      summary: Logout user
      responses:
        '200':
          description: User logged out successfully
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /auth/me:
    get:
      summary: Get authenticated user details
      responses:
        '200':
          description: Authenticated user details
          content:
            application/json:
              schema:
                type: object
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
  /users:
    get:
      summary: List all users
      responses:
        '200':
          description: List of all users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '500':
          description: Internal Server Error
    post:
      summary: Create a new user
      responses:
        '201':
          description: User created successfully
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /users/{id}:
    get:
      summary: 'Get user details for ID: {id}'
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                type: object
        '404':
          description: User not found
        '500':
          description: Internal Server Error
    put:
      summary: 'Update user details for ID: {id}'
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: User updated successfully
        '400':
          description: Bad Request
        '404':
          description: User not found
        '500':
          description: Internal Server Error
    delete:
      summary: 'Delete user with ID: {id}'
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '204':
          description: User deleted successfully
        '404':
          description: User not found
        '500':
          description: Internal Server Error
    patch:
      summary: 'Activate or Deactivate user with ID: {id}'
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: User status updated successfully
        '400':
          description: Bad Request
        '404':
          description: User not found
        '500':
          description: Internal Server Error
  /roles:
    get:
      summary: List all roles
      responses:
        '200':
          description: List of all roles
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '500':
          description: Internal Server Error
    post:
      summary: Create a new role
      responses:
        '201':
          description: Role created successfully
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /roles/{id}:
    get:
      summary: 'Get role details for ID: {id}'
      parameters:
      - name: id
        in: path
        description: Role ID
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: Role details
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Role not found
        '500':
          description: Internal Server Error
    put:
      summary: 'Update role details for ID: {id}'
      parameters:
      - name: id
        in: path
        description: Role ID
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: Role updated successfully
        '400':
          description: Bad Request
        '404':
          description: Role not found
        '500':
          description: Internal Server Error
    delete:
      summary: 'Delete role with ID: {id}'
      parameters:
      - name: id
        in: path
        description: Role ID
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '204':
          description: Role deleted successfully
        '404':
          description: Role not found
        '500':
          description: Internal Server Error
    patch:
      summary: 'Assign role with ID: {id}'
      parameters:
      - name: id
        in: path
        description: Role ID
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: Role assigned successfully
        '400':
          description: Bad Request
        '404':
          description: Role not found
        '500':
          description: Internal Server Error
  /admin/stats:
    get:
      summary: Get application statistics
      responses:
        '200':
          description: Application statistics
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
  /admin/users:
    get:
      summary: List users with admin-level filtering
      responses:
        '200':
          description: List of users with admin-level filtering
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '500':
          description: Internal Server Error
    delete:
      summary: Bulk delete users
      responses:
        '204':
          description: Users deleted successfully
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /admin/users/bulk:
    post:
      summary: Bulk create users
      responses:
        '201':
          description: Users created successfully
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /admin/logs:
    get:
      summary: Fetch application logs
      responses:
        '200':
          description: Application logs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '500':
          description: Internal Server Error
  /search/users:
    get:
      summary: Search for users based on criteria
      responses:
        '200':
          description: List of users matching the criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '500':
          description: Internal Server Error
  /search/roles:
    get:
      summary: Search for roles based on criteria
      responses:
        '200':
          description: List of roles matching the criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '500':
          description: Internal Server Error
  /config:
    get:
      summary: Get system configuration
      responses:
        '200':
          description: System configuration
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
    put:
      summary: Update system configuration
      responses:
        '200':
          description: System configuration updated successfully
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /audit/users/{id}:
    get:
      summary: 'Get audit logs for user with ID: {id}'
      parameters:
      - name: id
        in: path
        description: User ID
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: Audit logs for user
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '404':
          description: User not found
        '500':
          description: Internal Server Error
  /audit/roles/{id}:
    get:
      summary: 'Get audit logs for role with ID: {id}'
      parameters:
      - name: id
        in: path
        description: Role ID
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: Audit logs for role
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '404':
          description: Role not found
        '500':
          description: Internal Server Error
  /health:
    get:
      summary: Health check for the application
      responses:
        '200':
          description: Application health status
          content:
            application/json:
              schema:
                type: object
        '500':
          description: Internal Server Error
components:
  schemas: {}
