apiVersion: v1
kind: Service
metadata:
  name: user-management
  labels:
    app: user-management
spec:
  selector:
    app: user-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
